In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("Retail_Sales.csv")

In [3]:
df=pd.DataFrame(data)

In [4]:
df

,Transaction_ID,Date,Store_Location,Customer_ID,Product_Category,Units_Sold,Revenue (£),Discount_Applied (%),Customer_Age,Loyalty_Score
0,1.0,2024-01-01,Leeds,4958.0,Clothing,7.0,216.0,18.88,69.0,50.25
1,2.0,2024-01-02,London,4189.0,Electronics,19.0,471.0,7.57,46.0,63.63
2,3.0,NaN,Leeds,3087.0,Clothing,9.0,316.0,18.75,68.0,64.21
3,4.0,2024-01-04,Manchester,3367.0,Groceries,15.0,137.0,14.45,27.0,67.74
4,5.0,2024-01-05,Manchester,1160.0,NaN,9.0,99.0,29.06,21.0,92.33
...,...,...,...,...,...,...,...,...,...,...
95,96.0,2024-04-05,Manchester,3930.0,Electronics,3.0,390.0,6.79,26.0,94.79
96,97.0,2024-04-06,Manchester,NaN,Clothing,14.0,250.0,14.20,57.0,79.62
97,98.0,2024-04-07,London,1488.0,Electronics,11.0,32.0,21.77,63.0,39.27
98,99.0,2024-04-08,Manchester,2551.0,Electronics,14.0,168.0,29.08,21.0,72.71
99,100.0,2024-04-09,Manchester,4034.0,Clothing,16.0,NaN,7.53,35.0,38.30

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Transaction_ID        95 non-null     float64
 1   Date                  95 non-null     str
 2   Store_Location        95 non-null     str
 3   Customer_ID           95 non-null     float64
 4   Product_Category      95 non-null     str
 5   Units_Sold            95 non-null     float64
 6   Revenue (£)           95 non-null     float64
 7   Discount_Applied (%)  95 non-null     float64
 8   Customer_Age          95 non-null     float64
 9   Loyalty_Score         95 non-null     float64
dtypes: float64(7), str(3)
memory usage: 7.9 KB

In [6]:
df.isnull().sum()

Transaction_ID          5
Date                    5
Store_Location          5
Customer_ID             5
Product_Category        5
Units_Sold              5
Revenue (£)             5
Discount_Applied (%)    5
Customer_Age            5
Loyalty_Score           5
dtype: int64

In [7]:
df.dropna(inplace=True,ignore_index=True)

In [8]:
df

,Transaction_ID,Date,Store_Location,Customer_ID,Product_Category,Units_Sold,Revenue (£),Discount_Applied (%),Customer_Age,Loyalty_Score
0,1.0,2024-01-01,Leeds,4958.0,Clothing,7.0,216.0,18.88,69.0,50.25
1,2.0,2024-01-02,London,4189.0,Electronics,19.0,471.0,7.57,46.0,63.63
2,4.0,2024-01-04,Manchester,3367.0,Groceries,15.0,137.0,14.45,27.0,67.74
3,6.0,2024-01-06,Birmingham,3025.0,Groceries,17.0,342.0,19.91,57.0,64.91
4,8.0,2024-01-08,London,1416.0,Clothing,8.0,14.0,28.35,62.0,28.47
...,...,...,...,...,...,...,...,...,...,...
59,93.0,2024-04-02,Manchester,1126.0,Electronics,17.0,28.0,23.33,64.0,89.99
60,95.0,2024-04-04,London,2142.0,Clothing,8.0,286.0,19.23,39.0,68.19
61,96.0,2024-04-05,Manchester,3930.0,Electronics,3.0,390.0,6.79,26.0,94.79
62,98.0,2024-04-07,London,1488.0,Electronics,11.0,32.0,21.77,63.0,39.27
63,99.0,2024-04-08,Manchester,2551.0,Electronics,14.0,168.0,29.08,21.0,72.71

In [9]:
df=df.astype({"Transaction_ID":int,"Customer_ID":int,"Units_Sold":int,"Customer_Age":int})

In [10]:
df

,Transaction_ID,Date,Store_Location,Customer_ID,Product_Category,Units_Sold,Revenue (£),Discount_Applied (%),Customer_Age,Loyalty_Score
0,1,2024-01-01,Leeds,4958,Clothing,7,216.0,18.88,69,50.25
1,2,2024-01-02,London,4189,Electronics,19,471.0,7.57,46,63.63
2,4,2024-01-04,Manchester,3367,Groceries,15,137.0,14.45,27,67.74
3,6,2024-01-06,Birmingham,3025,Groceries,17,342.0,19.91,57,64.91
4,8,2024-01-08,London,1416,Clothing,8,14.0,28.35,62,28.47
...,...,...,...,...,...,...,...,...,...,...
59,93,2024-04-02,Manchester,1126,Electronics,17,28.0,23.33,64,89.99
60,95,2024-04-04,London,2142,Clothing,8,286.0,19.23,39,68.19
61,96,2024-04-05,Manchester,3930,Electronics,3,390.0,6.79,26,94.79
62,98,2024-04-07,London,1488,Electronics,11,32.0,21.77,63,39.27
63,99,2024-04-08,Manchester,2551,Electronics,14,168.0,29.08,21,72.71

In [11]:
df['Date'].dtypes

In [12]:
df['Date']=pd.to_datetime(df['Date'],format="mixed",errors='coerce')

In [14]:
df.to_csv("Sales_data.csv",index=False)